openapi: 3.0.0
info:
  title: Exemple API
  description: Description de votre API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /utilisateurs:
    get:
      summary: Récupérer tous les utilisateurs de sa mere
      responses:
        '200':
          description: Liste des utilisateurs récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nom:
                      type: string
                    age:
                      type: integer
    post:
      summary: Créer un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                age:
                  type: integer
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nom:
                    type: string
                  age:
                    type: integer
  /utilisateurs/{id}:
    get:
      summary: Récupérer un utilisateur par ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de l'utilisateur à récupérer
          schema:
            type: integer
      responses:
        '200':
          description: Utilisateur récupéré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nom:
                    type: string
                  age:
                    type: integer
        '404':
          description: Utilisateur non trouvé
    put:
      summary: Mettre à jour un utilisateur par ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de l'utilisateur à mettre à jour
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                age:
                  type: integer
      responses:
        '200':
          description: Utilisateur mis à jour avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nom:
                    type: string
                  age:
                    type: integer
        '404':
          description: Utilisateur non trouvé
    delete:
      summary: Supprimer un utilisateur par ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID de l'utilisateur à supprimer
          schema:
            type: integer
      responses:
        '204':
          description: Utilisateur supprimé avec succès
